spring:
  datasource:
    url: jdbc:mysql://mysql:3306/ecommerce_db
    username: ${USERNAME_DATABASE}
    password: ${PASSWORD_DATABASE}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: redis
      port: 6379

  rabbitmq:
    host: rabbitMq
    port: 5672
    username: ${USER_MQ}
    password: ${PASSWORD_MQ}